# Form implementation generated from reading ui file 'formulario.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(494, 422)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setStyleSheet("QFrame{\n"
"background-color:rgb(255, 255, 255)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(parent=self.frame)
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("QFrame{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton{\n"
"color: rgb(0,0,0);\n"
"font: 77 10pt \"Arial Black\";\n"
"border:0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(159, 159, 159);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_menu = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_menu.setMinimumSize(QtCore.QSize(100, 40))
        self.btn_menu.setMaximumSize(QtCore.QSize(200, 40))
        self.btn_menu.setStyleSheet("#Button{\n"
"border: 0;\n"
"}\n"
"#Button:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("iconos/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(22, 22))
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout.addWidget(self.btn_menu)
        spacerItem = QtWidgets.QSpacerItem(227, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_hidden = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_hidden.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_hidden.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_hidden.setStyleSheet("#Button{\n"
"border: 0;\n"
"}\n"
"#Button:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_hidden.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("iconos/hid.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_hidden.setIcon(icon1)
        self.btn_hidden.setIconSize(QtCore.QSize(38, 38))
        self.btn_hidden.setObjectName("btn_hidden")
        self.horizontalLayout.addWidget(self.btn_hidden)
        self.btn_minimizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_minimizar.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_minimizar.setStyleSheet("#Button{\n"
"border: 0;\n"
"}\n"
"#Button:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_minimizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("iconos/min.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_minimizar.setIcon(icon2)
        self.btn_minimizar.setIconSize(QtCore.QSize(24, 24))
        self.btn_minimizar.setObjectName("btn_minimizar")
        self.horizontalLayout.addWidget(self.btn_minimizar)
        self.btn_maximizar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_maximizar.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_maximizar.setStyleSheet("")
        self.btn_maximizar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("iconos/max.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_maximizar.setIcon(icon3)
        self.btn_maximizar.setIconSize(QtCore.QSize(24, 24))
        self.btn_maximizar.setObjectName("btn_maximizar")
        self.horizontalLayout.addWidget(self.btn_maximizar)
        self.btn_cerrar = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_cerrar.setStyleSheet("#Button{\n"
"border: 0;\n"
"}\n"
"#Button:hover{\n"
"background-color: rgb(195, 195, 195);\n"
"}")
        self.btn_cerrar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("iconos/cerrar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_cerrar.setIcon(icon4)
        self.btn_cerrar.setIconSize(QtCore.QSize(34, 34))
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.horizontalLayout.addWidget(self.btn_cerrar)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_contenido = QtWidgets.QFrame(parent=self.frame)
        self.frame_contenido.setStyleSheet("#frame_contenido{\n"
"background:rgb(231, 231, 231);\n"
"}\n"
"QFrame{\n"
"background:rgb(231, 231, 231);\n"
"}")
        self.frame_contenido.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_contenido.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_contenido.setObjectName("frame_contenido")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_contenido)
        self.horizontalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_controles = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_controles.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_controles.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_controles.setStyleSheet("QFrame{\n"
"background-color: rgb(222, 222, 222);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(159, 159, 159);\n"
"border-top-left-radius: 20px;\n"
"border-bottom-left-radius: 20px;\n"
"color: rgb(0,0,0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(200, 200, 200);\n"
"color: rgb(0, 0, 0);\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"")
        self.frame_controles.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_controles.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_controles.setObjectName("frame_controles")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_controles)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_PListar = QtWidgets.QPushButton(parent=self.frame_controles)
        self.btn_PListar.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_PListar.setMaximumSize(QtCore.QSize(100, 50))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("iconos/read.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_PListar.setIcon(icon5)
        self.btn_PListar.setIconSize(QtCore.QSize(20, 20))
        self.btn_PListar.setCheckable(False)
        self.btn_PListar.setChecked(False)
        self.btn_PListar.setAutoRepeat(False)
        self.btn_PListar.setAutoExclusive(False)
        self.btn_PListar.setAutoDefault(False)
        self.btn_PListar.setObjectName("btn_PListar")
        self.verticalLayout_5.addWidget(self.btn_PListar)
        self.btn_PCrear = QtWidgets.QPushButton(parent=self.frame_controles)
        self.btn_PCrear.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_PCrear.setMaximumSize(QtCore.QSize(100, 50))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("iconos/create.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_PCrear.setIcon(icon6)
        self.btn_PCrear.setIconSize(QtCore.QSize(20, 20))
        self.btn_PCrear.setObjectName("btn_PCrear")
        self.verticalLayout_5.addWidget(self.btn_PCrear)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 8)
        self.horizontalLayout_2.addWidget(self.frame_controles)
        self.frame_paginas = QtWidgets.QFrame(parent=self.frame_contenido)
        self.frame_paginas.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_paginas.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_paginas.setObjectName("frame_paginas")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_paginas)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_paginas)
        self.stackedWidget.setStyleSheet("QLabel{\n"
"font: 87 12pt \"Arial Black\";\n"
"color: #000;\n"
"border: 0;\n"
"}\n"
"QPushButton{\n"
"background-color:rgb(159, 159, 159);\n"
"border-radius: 20px;\n"
"color:#000;\n"
"font: 77 10pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(200, 200, 200);\n"
"}\n"
"QTableWidget{\n"
"background-color: rgb(255,255,255);\n"
"color: #000;\n"
"gridline-color: rgb(0,206,151);\n"
"font-size: 12pt;\n"
"}\n"
"QHeaderView::section{\n"
"color: #000;\n"
"border: 1px solid #000;\n"
"font-size: 12pt;\n"
"}\n"
"QTableWidget QTableCornerButton::section{\n"
"background-color: #000;\n"
"border: 1px solid rgb(0,206,151);\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_listar = QtWidgets.QWidget()
        self.page_listar.setObjectName("page_listar")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_listar)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(parent=self.page_listar)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.tabla_productos = QtWidgets.QTableWidget(parent=self.page_listar)
        self.tabla_productos.setObjectName("tabla_productos")
        self.tabla_productos.setColumnCount(4)
        self.tabla_productos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_productos.setHorizontalHeaderItem(3, item)
        self.verticalLayout_6.addWidget(self.tabla_productos)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_editar = QtWidgets.QPushButton(parent=self.page_listar)
        self.btn_editar.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_editar.setObjectName("btn_editar")
        self.horizontalLayout_3.addWidget(self.btn_editar)
        self.btn_eliminar = QtWidgets.QPushButton(parent=self.page_listar)
        self.btn_eliminar.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_3.addWidget(self.btn_eliminar)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.page_listar)
        self.page_editar = QtWidgets.QWidget()
        self.page_editar.setObjectName("page_editar")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_editar)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_6.setMinimumSize(QtCore.QSize(0, 50))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_id = QtWidgets.QLabel(parent=self.page_editar)
        self.label_id.setObjectName("label_id")
        self.verticalLayout_8.addWidget(self.label_id)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.lineEdit_codigo_2 = QtWidgets.QLineEdit(parent=self.page_editar)
        self.lineEdit_codigo_2.setObjectName("lineEdit_codigo_2")
        self.horizontalLayout_10.addWidget(self.lineEdit_codigo_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.lineEdit_producto_2 = QtWidgets.QLineEdit(parent=self.page_editar)
        self.lineEdit_producto_2.setObjectName("lineEdit_producto_2")
        self.horizontalLayout_11.addWidget(self.lineEdit_producto_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.lineEdit_precio_2 = QtWidgets.QLineEdit(parent=self.page_editar)
        self.lineEdit_precio_2.setObjectName("lineEdit_precio_2")
        self.horizontalLayout_12.addWidget(self.lineEdit_precio_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.btn_guardar_cambios = QtWidgets.QPushButton(parent=self.page_editar)
        self.btn_guardar_cambios.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_guardar_cambios.setObjectName("btn_guardar_cambios")
        self.horizontalLayout_9.addWidget(self.btn_guardar_cambios)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.stackedWidget.addWidget(self.page_editar)
        self.page_crear = QtWidgets.QWidget()
        self.page_crear.setObjectName("page_crear")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_crear)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.page_crear)
        self.label_5.setMinimumSize(QtCore.QSize(0, 50))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.page_crear)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_codigo = QtWidgets.QLineEdit(parent=self.page_crear)
        self.lineEdit_codigo.setObjectName("lineEdit_codigo")
        self.horizontalLayout_4.addWidget(self.lineEdit_codigo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.page_crear)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_producto = QtWidgets.QLineEdit(parent=self.page_crear)
        self.lineEdit_producto.setObjectName("lineEdit_producto")
        self.horizontalLayout_5.addWidget(self.lineEdit_producto)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.page_crear)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit_precio = QtWidgets.QLineEdit(parent=self.page_crear)
        self.lineEdit_precio.setObjectName("lineEdit_precio")
        self.horizontalLayout_6.addWidget(self.lineEdit_precio)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.btn_crear = QtWidgets.QPushButton(parent=self.page_crear)
        self.btn_crear.setMinimumSize(QtCore.QSize(100, 50))
        self.btn_crear.setObjectName("btn_crear")
        self.horizontalLayout_7.addWidget(self.btn_crear)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.stackedWidget.addWidget(self.page_crear)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_paginas)
        self.verticalLayout_2.addWidget(self.frame_contenido)
        self.horizontalLayout_13.addWidget(self.frame)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.btn_cerrar, self.btn_maximizar)
        Form.setTabOrder(self.btn_maximizar, self.btn_minimizar)
        Form.setTabOrder(self.btn_minimizar, self.btn_hidden)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_PListar.setText(_translate("Form", "  LISTAR"))
        self.btn_PCrear.setText(_translate("Form", "  CREAR"))
        self.label.setText(_translate("Form", "Lista de productos"))
        item = self.tabla_productos.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tabla_productos.horizontalHeaderItem(1)
        item.setText(_translate("Form", "CODIGO"))
        item = self.tabla_productos.horizontalHeaderItem(2)
        item.setText(_translate("Form", "PRODUCTO"))
        item = self.tabla_productos.horizontalHeaderItem(3)
        item.setText(_translate("Form", "PRECIO"))
        self.btn_editar.setText(_translate("Form", "EDITAR"))
        self.btn_eliminar.setText(_translate("Form", "ELIMINAR"))
        self.label_6.setText(_translate("Form", "EDITAR PRODUCTO"))
        self.label_id.setText(_translate("Form", "id"))
        self.label_8.setText(_translate("Form", "CODIGO"))
        self.label_9.setText(_translate("Form", "PRODUCTO"))
        self.label_10.setText(_translate("Form", "PRECIO"))
        self.btn_guardar_cambios.setText(_translate("Form", "GUARDAR CAMBIOS"))
        self.label_5.setText(_translate("Form", "CREAR PRODUCTO"))
        self.label_2.setText(_translate("Form", "CODIGO"))
        self.label_3.setText(_translate("Form", "PRODUCTO"))
        self.label_4.setText(_translate("Form", "PRECIO"))
        self.btn_crear.setText(_translate("Form", "CREAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
